import { stageRank, isPostFlash, matchesDevice, canPrepare, hasRootProof } from './workflow-view.js';

const NAV = [['overview', 'Overview', '01'], ['prepare', 'Preparation', '02'], ['flash', 'Flash', '03'], ['logs', 'Checks & logs', '04']];
const STEPS = [['device-check', 'Device detected'], ['firmware-valid', 'Firmware validated'], ['patched-ap', 'AP patched'], ['preflight-ok', 'Preflight passed'], ['flash-approved', 'Approval recorded'], ['waiting-boot', 'Engine finished'], ['rooted', 'Root verified']];
const EMPTY_ACTIONS = {};

export default function WorkbenchView({device, session, busy = false, error = '', rootProof, preflight, engine, database, job, log = [], approved = false, flashCmd = '', patchPath = '', downloadIdentity, activeTab = 'overview', onTab = () => {}, actions = EMPTY_ACTIONS}) {
  const samePhone = matchesDevice(session, device);
  const postFlash = isPostFlash(session);
  const proven = samePhone && rootProof?.serial === device?.serial && hasRootProof(rootProof);
  const prepareOK = canPrepare(session, device);
  const flashLocked = busy || postFlash || device?.rooted || !samePhone || !preflight?.ok;
  const stage = session?.stage || 'not started';
  const meta = [
    ['Model', device?.model || session?.model], ['Serial ADB', device?.serial || session?.serial],
    ['Android', device?.androidVersion], ['PDA / build', device?.buildVersion],
    ['CSC', device?.salesCode], ['Binary', device?.binaryBit],
    ['Bootloader', device ? (device.bootloaderLocked ? 'Locked' : 'Unlocked') : null], ['Verified boot', device?.verifiedBootState],
  ];
  return <div className="workbench">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark" aria-hidden="true">AR</span><div>AutoRoot<small>DEVICE WORKBENCH</small></div></div>
      <div className="sidebar-label">WORKSPACE</div>
      <nav aria-label="Workspace navigation">{NAV.map(([key, title, number]) => <button key={key} className={`nav-item ${activeTab === key ? 'selected' : ''}`} aria-current={activeTab === key ? 'page' : undefined} onClick={() => onTab(key)}><span>{number}</span>{title}</button>)}</nav>
      <div className="sidebar-device"><span className="sidebar-label">TESTED CONFIGURATION</span><strong>Samsung Galaxy A06</strong><code>SM-A065F · XID · Binary 4</code><p>Magisk 30.7 / English<br/>Windows x64</p><span className="sidebar-label">CONNECTED DEVICE</span><strong>{device?.model || 'No device connected'}</strong><code>{device?.serial || 'Refresh to check ADB'}</code><p>Other configurations are not validated.</p></div>
      <div className="sidebar-footer"><span className="tag tag-neutral">EXPERIMENTAL</span><p>Approvals remain with the operator.</p></div>
    </aside>

    <main className="main">
      <header className="topbar"><div><div className="eyebrow">AUTOROOT / {activeTab === 'overview' ? 'OVERVIEW' : activeTab.toUpperCase()}</div><h1>{NAV.find(([key]) => key === activeTab)?.[1]}</h1></div><button className="button" disabled={busy} onClick={actions.reconnect}>Refresh connection</button></header>
      <div className="statusbar"><span><i className={`status-dot ${device ? 'online' : ''}`}/>{device ? 'ADB connected' : 'ADB disconnected'}</span><span className="status-separator"/><code>{device?.model || session?.model || 'No device'}</code><span className="status-stage">Session <code>{stage}</code></span></div>
      {error && <div className="notice error-notice" role="alert"><strong>Needs attention</strong><span>{error}</span></div>}
      {busy && <div className="notice busy-notice" role="status"><span className="busy-indicator"/>Operation in progress. Wait for the result before continuing.{job?.status === 'running' && <code>{job.operation}</code>}</div>}

      {activeTab === 'overview' && <>
        <section className={`outcome ${proven ? 'outcome-success' : ''}`}><div><div className="eyebrow">DEVICE STATUS</div><h2>{proven ? 'Root verified.' : !device ? 'Waiting for a device.' : 'Check root access.'}</h2><p>{proven ? 'A live check returned uid=0. No repeat flash is needed.' : 'Connect USB, authorize debugging, then run a check. A saved session is not proof of current root access.'}</p></div><div className="outcome-action"><span className={`tag ${proven ? 'tag-success' : 'tag-neutral'}`}>{proven ? 'ROOTED: YES' : 'NOT VERIFIED'}</span><button className="button primary" disabled={busy || !samePhone} onClick={actions.verify}>Verify root</button></div>{proven && <pre className="proof" aria-label="Root access evidence">{rootProof.raw}</pre>}</section>
        <div className="two-column"><section className="panel"><div className="panel-heading"><h2>Device identity</h2><span className="section-number">01</span></div><dl className="device-data">{meta.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value || '—'}</dd></div>)}</dl></section><section className="panel"><div className="panel-heading"><h2>Session history</h2><span className="section-number">02</span></div><ol className="timeline">{STEPS.map(([key, title], index) => <li key={key} className={stageRank(stage) >= stageRank(key) ? 'complete' : ''}><span className="step-number">{String(index + 1).padStart(2, '0')}</span><span>{title}</span><span className="step-state">{stageRank(stage) >= stageRank(key) ? 'DONE' : 'PENDING'}</span></li>)}</ol></section></div>
        <section className="panel compact-panel"><div><h2>New test from stock</h2><p>Restore stock separately first. The previous session is archived; this button does not wipe or flash the phone.</p></div><button className="button" disabled={busy || !samePhone || device?.rooted || device?.bootloaderLocked || ['download-mode', 'flashing'].includes(stage)} onClick={actions.newRun}>Start a new PoC session</button></section>
        {postFlash && <section className="panel"><div className="panel-heading"><h2>Post-flash checkpoints</h2><span className="tag tag-neutral">OPERATOR</span></div><ol className="plain-steps"><li>If Recovery requests a factory reset, perform the approved reset. Do not flash again or relock.</li><li>Complete Android setup to Home; enable and authorize USB debugging.</li><li>Install/open the full Magisk app, complete additional setup and reboot if requested.</li><li>Authorize ADB again, then verify root. Approve the Shell Superuser request yourself.</li></ol></section>}
      </>}

      {activeTab === 'prepare' && <>
        <div className="page-intro"><h2>Prepare the right package.</h2><p>Follow these steps on a stock, unrooted phone with an unlocked bootloader. Already-rooted devices do not need to repeat them.</p></div>
        <section className="panel"><div className="panel-heading"><h2><span className="section-number">01</span> Firmware</h2><span className="tag tag-neutral">{database?.source === 'local' ? 'LOCAL FILE' : 'SOURCE NOT READY'}</span></div><dl className="inline-data"><div><dt>Database PDA</dt><dd>{database?.record?.pda || '—'}</dd></div><div><dt>CSC build</dt><dd>{database?.record?.csc || '—'}</dd></div><div><dt>Binary</dt><dd>{database?.record?.bootloaderBinary || '—'}</dd></div></dl><p>The database selects matching metadata. This PoC uses a local stock ZIP; network firmware download has not been tested.</p><div className="button-row"><button className="button primary" disabled={busy || !prepareOK || !database?.ready} onClick={actions.database}>Select & validate from database</button><button className="button" disabled={busy || !prepareOK} onClick={actions.localFirmware}>Choose local ZIP</button></div></section>
        <section className="panel"><div className="panel-heading"><h2><span className="section-number">02</span> Magisk patch</h2><span className="tag tag-neutral">ON THE SAME PHONE</span></div><p>Requires English Magisk 30.7, Ramdisk Yes and an unlocked screen. Unrecognized screens stop the operation.</p><div className="button-row"><button className="button" disabled={busy || !prepareOK || stage !== 'firmware-valid'} onClick={actions.preparePatch}>Install Magisk & transfer AP</button><button className="button primary" disabled={busy || !prepareOK || stage !== 'firmware-valid' || !session?.artifacts?.remoteAP} onClick={actions.autoPatch}>Patch & collect automatically</button></div><details className="details"><summary>Collect a manually patched file</summary><label className="field-label" htmlFor="patch-path">New output path on the phone</label><div className="input-row"><input id="patch-path" placeholder="/sdcard/Download/magisk_patched-30700_XXXXX.tar" value={patchPath} onChange={event => actions.patchPath?.(event.target.value)}/><button className="button" disabled={busy || !prepareOK || !patchPath} onClick={actions.collect}>Collect & validate</button></div></details></section>
        <section className="panel"><div className="panel-heading"><h2><span className="section-number">03</span> Download Mode identity</h2><span className={`tag ${engine?.available ? 'tag-success' : 'tag-neutral'}`}>{engine?.available ? 'ENGINE VERIFIED' : 'ENGINE NOT READY'}</span></div><p>The probe reads identity/PIT only. Restart the phone manually afterwards. This does not authorize flashing.</p><code className="file-path">{engine?.available ? `samloader ${engine.version} · ${engine.path}` : engine?.reason || 'Not checked'}</code><div className="button-row"><button className="button" disabled={busy || postFlash || !samePhone || !engine?.available} onClick={actions.probe}>Read-only engine probe</button>{downloadIdentity && <button className="button primary" disabled={busy} onClick={actions.bind}>Confirm identity pairing</button>}</div>{downloadIdentity && <pre className="proof">ADB: {downloadIdentity.adbSerial}{'\n'}Download Mode: {downloadIdentity.downloadSerial}</pre>}</section>
      </>}

      {activeTab === 'flash' && <>
        <div className="page-intro"><h2>Check. Approve. Flash.</h2><p>Initial-root wipes data. The backend rechecks all requirements before writing.</p></div>
        {postFlash && <div className="notice"><strong>Flashing has already run in this session.</strong><span>Continue setup and verification in Overview. There is no automatic retry.</span></div>}
        <section className="panel"><div className="panel-heading"><h2>Preflight</h2><span className={`tag ${preflight?.ok && !postFlash ? 'tag-success' : 'tag-neutral'}`}>{postFlash ? 'NO REPEAT FLASH' : preflight?.ok ? 'PASSED' : 'LOCKED'}</span></div>{!postFlash && preflight ? <ul className="check-list">{preflight.checks?.map(check => <li key={check.id}><span className={`check-mark ${check.passed ? 'pass' : 'fail'}`}>{check.passed ? 'OK' : 'STOP'}</span><div><strong>{check.label}</strong>{check.detail && <small>{check.detail}</small>}</div></li>)}</ul> : <p>{postFlash ? 'Initial-root preflight is not a health check for an already-rooted phone.' : 'No result yet. Run preflight once firmware, patch and identity are ready.'}</p>}<div className="button-row"><button className="button" disabled={busy || postFlash || !samePhone} onClick={actions.preflight}>Refresh preflight</button><button className="button" disabled={busy || postFlash || !samePhone} onClick={actions.dryRun}>Dry run without flashing</button></div></section>
        <section className="panel flash-panel"><div className="panel-heading"><h2>Approval & execution</h2><span className="tag tag-warning">WIPES DATA</span></div><p>Approval is bound to the phone and file checksums. Do not disconnect USB, close the app or shut down the laptop during flashing.</p><div className="button-row"><button className="button" disabled={flashLocked} onClick={actions.approve}>Approve plan</button><button className="button" disabled={busy || postFlash || !approved} onClick={actions.plan}>Show command</button><button className="button danger" disabled={flashLocked || !approved} onClick={actions.flash}>Flash & wipe data</button></div>{flashCmd && <pre className="terminal">{flashCmd}</pre>}<p className="fine-print">Root is confirmed only after boot and a uid=0 check, not from the engine exit code.</p></section>
      </>}

      {activeTab === 'logs' && <>
        {session?.stage === 'failed' && <section className="panel"><div className="panel-heading"><h2>Failed session recovery</h2><span className="tag tag-warning">NO AUTOMATIC RETRY</span></div><p>Only a proven process-start failure can be recovered. Unknown or started flashes remain blocked. Evidence is archived and approval revoked after fresh checks.</p><button className="button" disabled={busy || !samePhone || device?.rooted} onClick={actions.recover}>Recover pre-launch failure (no flash)</button></section>}
        <section className="panel"><div className="panel-heading"><h2>Engine launch diagnostic</h2><span className="tag tag-neutral">NO FLASH</span></div><p>Run --version through the backend with the same output routing as flash. No phone access, session reset or retry.</p><button className="button" disabled={busy} onClick={actions.diagnose}>Test engine launch (no flash)</button></section>
        <section className="panel"><div className="panel-heading"><h2>Live verification</h2><span className={`tag ${proven ? 'tag-success' : 'tag-neutral'}`}>{proven ? 'UID=0' : 'NOT VERIFIED'}</span></div><p>Evidence comes from su -c id on the connected device.</p><button className="button primary" disabled={busy || !samePhone} onClick={actions.verify}>Verify root</button>{rootProof?.serial === device?.serial && rootProof?.raw && <pre className="proof">{rootProof.raw}</pre>}</section>
        <section className="panel log-panel"><div className="panel-heading"><h2>Activity log</h2><span className="section-number">{String(log.length).padStart(2, '0')}</span></div>{job && <div className="job-meta"><code>{job.operation}</code><span>{job.status}</span><small>{job.operation === 'executeFlash' && job.status === 'running' ? 'Transfer progress is unavailable. Do not disconnect USB.' : `${job.detail || ''} ${job.percent || 0}%`}</small></div>}<pre className="terminal" role="log">{log.join('\n') || 'No activity in this window yet.'}</pre><p className="fine-print">Hash progress applies to the current file, not the whole workflow or flash transfer. Engine logs are saved in bin/state/logs.</p></section>
      </>}
      <footer className="main-footer"><span>AutoRoot · guarded automation</span><span>Tested on SM-A065F only</span></footer>
    </main>
  </div>;
}
